# =============================================================================
# CONFIGURATION & CONSTANTS
# =============================================================================

MOOD_KEYWORDS = {
    "happy": [
        "happy",
        "excited",
        "great",
        "amazing",
        "awesome",
        "party",
        "energetic",
        "upbeat",
        "cheerful",
        "joyful",
        "senang",
        "gembira",
        "bahagia",
        "lit",
        "celebrate",
        "fun",
        # Aktivitas yang mengindikasikan mood happy
        "makan pagi",
        "sarapan",
        "breakfast",
        "morning",
        "pagi",
        "bangun tidur",
        "workout",
        "gym",
        "olahraga",
        "jalan-jalan",
        "hangout",
        "nongkrong",
        "party",
        "main",
        "weekend",
        "liburan",
        "vacation",
        "shopping",
        "belanja",
        "traveling",
        "wisata",
        "keluarga",
        "family",
        "teman",
        "friends",
        "ulang tahun",
        "birthday",
        "anniversary",
        "lulus",
        "graduation",
        "kerja",
        "work",
        "project",
        "achievement",
        "success",
        # Kata-kata positif umum
        "good",
        "bagus",
        "mantap",
        "keren",
        "oke",
        "sip",
        "asik",
        "seru",
        "enjoy",
    ],
    "sad": [
        "sad",
        "down",
        "depressed",
        "heartbroken",
        "lonely",
        "melancholy",
        "blue",
        "upset",
        "crying",
        "emotional",
        "galau",
        "sedih",
        "mellow",
        "broken",
        "hurt",
        "pain",
        # Situasi yang mengindikasikan mood sad
        "putus",
        "breakup",
        "pisah",
        "kehilangan",
        "lost",
        "gagal",
        "fail",
        "stress",
        "capek",
        "tired",
        "lelah",
        "bosan",
        "boring",
        "sepi",
        "sendiri",
        "alone",
        "kangen",
        "miss",
        "rindu",
        "hujan",
        "rain",
        "malam",
        "night",
        "insomnia",
        "overthinking",
        "anxiety",
        "cemas",
        "khawatir",
        "worry",
        "problem",
        "masalah",
    ],
    "neutral": [
        "okay",
        "fine",
        "normal",
        "chill",
        "relaxed",
        "calm",
        "casual",
        "balanced",
        "peaceful",
        "santai",
        "netral",
        "biasa",
        "relax",
        "standard",
        "usual",
        # Aktivitas netral
        "belajar",
        "study",
        "kerja",
        "work",
        "fokus",
        "focus",
        "konsentrasi",
        "reading",
        "baca",
        "menulis",
        "writing",
        "meditation",
        "meditasi",
        "yoga",
        "istirahat",
        "rest",
    ],
}

MOOD_EMOJIS = {
    "happy": "😊",
    "sad": "😢",
    "neutral": "😌",
    "energetic": "⚡",
    "melancholic": "🌙",
    "uplifting": "☀️",
    "cheerful": "😄",
    "emotional": "💭",
    "groovy": "🕺",
    "ambient": "🌊",
}

GENRE_EMOJIS = {
    "Pop": "🎤",
    "Hip-Hop": "🎤",
    "Rock": "🎸",
    "Electronic": "🎛️",
    "R&B": "🎷",
    "Jazz": "🎺",
    "Country": "🤠",
    "Latin": "💃",
    "K-Pop": "🌟",
    "Indie": "🎭",
    "Alternative": "🎨",
    "Rap": "🎤",
}

# Import optional dependencies with fallbacks
try:
    from googlesearch import search as google_search

    SEARCH_AVAILABLE = True
except ImportError:
    SEARCH_AVAILABLE = False

try:
    from langchain.agents import AgentType, Tool, initialize_agent
    from langchain.memory import ConversationBufferMemory
    from langchain_cohere import ChatCohere

    LLM_AVAILABLE = True
except ImportError:
    LLM_AVAILABLE = False
