# =============================================================================
# CONFIGURATION & CONSTANTS
# =============================================================================

# Mood keywords for advanced mood detection
MOOD_KEYWORDS = {
    "happy": [
        # --- Emosi Positif Inti ---
        "happy",
        "excited",
        "great",
        "amazing",
        "awesome",
        "cheerful",
        "joyful",
        "blessed",
        "senang",
        "gembira",
        "bahagia",
        "sumringah",
        "girang",
        # --- Slang & Ekspresi Positif ---
        "lit",
        "hype",
        "good mood",
        "good vibes",
        "mantap",
        "keren",
        "asik",
        "seru",
        "wih",
        "gokil",
        "pecah",
        "enjoy",
        "fun",
        # --- Aktivitas & Momen Bahagia ---
        "party",
        "celebrate",
        "ulang tahun",
        "birthday",
        "anniversary",
        "lulus",
        "graduation",
        "promosi",
        "promotion",
        "achievement",
        "success",
        "menang",
        "diterima",
        "gajian",
        "payday",
        "makan pagi",
        "sarapan",
        "breakfast",
        "morning",
        "pagi cerah",
        "sunrise",
        "jalan-jalan",
        "hangout",
        "nongkrong",
        "main",
        "kumpul",
        "reuni",
        "weekend",
        "liburan",
        "vacation",
        "healing",
        "traveling",
        "wisata",
        "belanja",
        "shopping",
        "dapat hadiah",
        "gift",
        "keluarga",
        "family",
        "teman",
        "friends",
        # --- Digabung dari Kategori 'Energetic' ---
        "energetic",
        "upbeat",
        "pumped up",
        "motivated",
        "semangat",
        "membara",
        "workout",
        "gym",
        "olahraga",
        "lari",
        "running",
        "jogging",
        "nge-gym",
        "bersepeda",
        "cycling",
        "dance",
        "menari",
        "zumba",
        "siap-siap",
        "on the way",
        "otw",
        "perjalanan",
        "commute",
        "pre-party",
        "sebelum manggung",
        "butuh semangat",
        "biar melek",
        # --- Digabung dari Kategori 'Romantic' (Vibe Positif) ---
        "love",
        "in love",
        "romantic",
        "cinta",
        "kasmaran",
        "sayang",
        "crush",
        "gebetan",
        "bucin",
        "lovely",
        "sweet",
        "butterflies in stomach",
        "kencan",
        "date night",
        "dinner",
        "berduaan",
        "jatuh cinta",
        "nembak",
        "ditembak",
        "jadian",
        "valentine",
    ],
    "sad": [
        # --- Emosi Negatif Inti ---
        "sad",
        "down",
        "depressed",
        "heartbroken",
        "lonely",
        "melancholy",
        "blue",
        "upset",
        "crying",
        "emotional",
        "galau",
        "sedih",
        "mellow",
        "patah hati",
        "kecewa",
        "nelangsa",
        "murung",
        # --- Slang & Ekspresi Negatif ---
        "broken",
        "hurt",
        "pain",
        "empty",
        "hampa",
        "remuk",
        "ambyar",
        "bad mood",
        # --- Situasi & Momen Sedih ---
        "putus",
        "breakup",
        "pisah",
        "ditinggal",
        "ghosting",
        "kehilangan",
        "lost",
        "gagal",
        "fail",
        "ditolak",
        "rejection",
        "stress",
        "capek",
        "tired",
        "lelah",
        "burnout",
        "sumpek",
        "penat",
        "sepi",
        "sendiri",
        "alone",
        "kesepian",
        "kangen",
        "miss",
        "rindu",
        "hujan",
        "rain",
        "mendung",
        "gloomy",
        "malam",
        "night",
        "tengah malam",
        "midnight",
        "begadang",
        "insomnia",
        "overthinking",
        "anxiety",
        "cemas",
        "khawatir",
        "worry",
        "gelisah",
        "problem",
        "masalah",
        "berantem",
        "konflik",
        "lagi ga baik-baik aja",
    ],
    "neutral": [
        # --- Mood & Keadaan Netral ---
        "okay",
        "fine",
        "normal",
        "casual",
        "balanced",
        "biasa aja",
        "netral",
        "standard",
        "usual",
        "calm",
        "chill",
        "relaxed",
        "peaceful",
        "serene",
        "tenang",
        "damai",
        "santai",
        "selow",
        "rileks",
        # --- Aktivitas Fokus & Santai ---
        "belajar",
        "study",
        "nugas",
        "mengerjakan tugas",
        "deadline",
        "fokus",
        "focus",
        "konsentrasi",
        "concentration",
        "kerja",
        "work",
        "wfh",
        "wfc",
        "di kantor",
        "baca",
        "reading",
        "menulis",
        "writing",
        "meditasi",
        "meditation",
        "yoga",
        "kontemplasi",
        "merenung",
        "istirahat",
        "rest",
        "leyeh-leyeh",
        # --- Momen Transisi & Lainnya ---
        "pulang kerja",
        "after work",
        "sore",
        "afternoon",
        "senja",
        "sunset",
        "minum teh",
        "ngopi",
        "coffee time",
        "tea time",
        "gabut",
        "boring",
        "bosan",  # Diarahkan ke musik chill/latar
    ],
    "energetic": [
        "semangat",
        "energi",
        "powerful",
        "strong",
        "workout",
        "gym",
        "olahraga",
        "exercise",
        "pump",
        "intense",
        "hyper",
        "adrenaline",
        "dynamic",
        "vigorous",
    ],
    "calm": [
        "tenang",
        "santai",
        "relax",
        "peaceful",
        "chill",
        "cool",
        "slow",
        "soft",
        "gentle",
        "soothing",
        "tranquil",
        "serene",
        "meditation",
        "zen",
    ],
    "romantic": [
        "romantis",
        "cinta",
        "love",
        "sayang",
        "couple",
        "valentine",
        "sweet",
        "tender",
        "intimate",
        "passionate",
        "affection",
        "heart",
    ],
    "melancholic": [
        "melankolis",
        "nostalgia",
        "rindu",
        "kenangan",
        "memories",
        "past",
        "wistful",
        "bittersweet",
        "longing",
    ],
}

# Emoji mappings for moods and genres
MOOD_EMOJIS = {
    "happy": "😊",
    "sad": "😢",
    "energetic": "⚡",
    "calm": "🧘‍♀️",
    "romantic": "💕",
    "neutral": "😐",
    "melancholic": "🌙",
}

GENRE_EMOJIS = {
    "pop": "🎤",
    "rock": "🎸",
    "jazz": "🎺",
    "classical": "🎼",
    "electronic": "🎛️",
    "hip-hop": "🎤",
    "r&b": "🎵",
    "country": "🎻",
    "folk": "🪕",
    "reggae": "🏝️",
    "blues": "🎷",
    "alternative": "🎸",
    "indie": "🎧",
    "dance": "💃",
    "ambient": "🌌",
}

# Import optional dependencies with fallbacks
try:
    from googlesearch import search as google_search

    SEARCH_AVAILABLE = True
except ImportError:
    SEARCH_AVAILABLE = False

try:
    from langchain.agents import AgentType, Tool, initialize_agent
    from langchain.memory import ConversationBufferMemory
    from langchain_cohere import ChatCohere

    LLM_AVAILABLE = True
except ImportError:
    LLM_AVAILABLE = False
